### ISSUE TITLE
bower dependencies not installing correctly

### ISSUE THREAD

**Issue by fredyrsam** [CarlosOV/generator-wass#1]
I made the installation of the generator and when generating a module and running it with "npm start" brought me a missing dependency bower error. I had to do "bower i" to solve the problem.

**Comment by CarlosOV** [comment]
The generator automatically install the bower dependencies, as long as you have the bower correctly installed. I will update the readme so that the steps are shown correctly. Thanks for the feedback.

**Comment by fredyrsam** [comment]
Ok, keep up the good work!
